### ISSUE TITLE
Some syntax errors in property access

### ISSUE THREAD

**Issue by gdl-888** [LostMyCode/javascript-deobfuscator#19]
![image](https://user-images.githubusercontent.com/55873929/99874385-fe33fa80-2c2a-11eb-8665-ec3b44a42c0d.png)
In the second property access, there should be a dot in the ret circle, but there is a space. This bug happens with differend JS codes too. 

```diff
- _0x562f9a.target tagName
+ _0x562f9a.target.tagName
```

*However, some parts work fine - like* `window.document.createElement`. It does not become `window.document createElement`.

**Comment by LostMyCode** [comment]
Thanks for the report.
I didnt realize but the bug occurs because of wrong escape :(

Deobfuscator replaces **xxx['yyy']** to **xxx.yyy** but escape if **xxx** is get or set.
Like replace set['yyy'] to set yyy (for setter)
tar**get**['tagName'] includes 'get' so yeah...

Anyway, I need to fix it. Thank you!

**Comment by LostMyCode** [comment]
Fixed (close)
